#!/usr/bin/env python3
"""Generate CUTLASS GEMM instance declarations for the ggml-cutlass backend.

This is a *template* / reference script. It does not depend on CuteDSL being
installed; instead, it emits a small C++ header listing the GEMM tile
configurations the backend would like to instantiate. When CuteDSL is
available, this script is the natural place to call into it and emit per-
instance .cu files.

The generated header is consumed by gemm_f16.cu when the project is
configured with `-DGGML_CUTLASS_USE_DSL=ON`.

Usage:
    generate_gemm_instances.py --output gemm_instances.inc
"""

from __future__ import annotations

import argparse
import os
import sys
import textwrap
from dataclasses import dataclass
from typing import Iterable


@dataclass(frozen=True)
class GemmTile:
    """A single GEMM tile configuration we want CUTLASS to instantiate."""

    name: str          # short tag, e.g. "sm80_f16_128x128x32"
    sm: int            # target SM architecture (e.g. 80)
    elem_a: str        # CUTLASS element type for A
    elem_b: str        # CUTLASS element type for B
    elem_c: str        # CUTLASS element type for C/D
    elem_acc: str      # accumulator element type (typically float)
    tile_m: int
    tile_n: int
    tile_k: int
    stages: int        # software pipeline stages

    @property
    def macro(self) -> str:
        return f"GGML_CUTLASS_GEMM_INSTANCE_{self.name.upper()}"


# A small starter set of tile shapes covering a range of problem sizes that
# show up in LLM inference. Real production code will sweep this list and
# pick the best instance per problem at dispatch time.
DEFAULT_TILES: tuple[GemmTile, ...] = (
    GemmTile("sm80_f16_64x64x32",    80, "half_t", "half_t", "half_t", "float",  64,  64,  32, 4),
    GemmTile("sm80_f16_128x128x32",  80, "half_t", "half_t", "half_t", "float", 128, 128,  32, 3),
    GemmTile("sm80_f16_128x256x32",  80, "half_t", "half_t", "half_t", "float", 128, 256,  32, 3),
    GemmTile("sm80_f16_256x128x32",  80, "half_t", "half_t", "half_t", "float", 256, 128,  32, 3),
    GemmTile("sm90_f16_128x128x64",  90, "half_t", "half_t", "half_t", "float", 128, 128,  64, 5),
)


HEADER_PREAMBLE = """\
// =============================================================================
// AUTO-GENERATED by ggml/src/ggml-cutlass/scripts/generate_gemm_instances.py
// DO NOT EDIT BY HAND.
//
// This header lists the CUTLASS GEMM instances that ggml-cutlass would like
// the build system to compile. When CuteDSL is wired up, replace the macros
// below with actual `using ... = cutlass::gemm::collective::CollectiveBuilder<...>`
// declarations.
// =============================================================================

#pragma once

"""


def _emit_tile(tile: GemmTile) -> str:
    return textwrap.dedent(f"""\
        // {tile.name}: SM{tile.sm}, MNK={tile.tile_m}x{tile.tile_n}x{tile.tile_k}, stages={tile.stages}
        #define {tile.macro} \\
            /* sm={tile.sm} elements={tile.elem_a},{tile.elem_b},{tile.elem_c},acc={tile.elem_acc} */ \\
            /* tile=({tile.tile_m},{tile.tile_n},{tile.tile_k}) stages={tile.stages} */ \\
            // CollectiveBuilder<...> placeholder

        """)


def emit(tiles: Iterable[GemmTile]) -> str:
    body = "".join(_emit_tile(t) for t in tiles)
    registry = "\n".join(f"// - {t.name}" for t in tiles)
    return (
        HEADER_PREAMBLE
        + "// Available instances:\n"
        + registry
        + "\n\n"
        + body
    )


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True,
                        help="Path to the generated .inc file.")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)

    out_dir = os.path.dirname(os.path.abspath(args.output))
    os.makedirs(out_dir, exist_ok=True)

    contents = emit(DEFAULT_TILES)
    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write(contents)

    print(f"[ggml-cutlass] wrote {len(DEFAULT_TILES)} instance(s) to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
